export const RelacionamentoElements = {
    // Login Page
    txt_user: 'input[id="mat-input-0"]',
    txt_password: 'input[id="mat-input-1"]',
    btn_log_in: 'button[type="submit"]',
    //acessos do ENCARTE
    txt_descricao:'textarea[formcontrolname="des_oferta_encarte"]',
    txt_inicio: 'input[formcontrolname="dat_inicio"]',
    txt_final:'input[formcontrolname="dat_fim"]',
    //ativarEncarteDestaque:'span[class="mat-slide-toggle-bar"]',
    btn_novaImg: 'button[class="mat-focus-indicator button-dark button-NovoItem mat-button mat-button-base"]',
    txt_linkImg: 'input[data-placeholder="Endereço da imagem"]',
    btn_salvarImg : 'button[class="mat-focus-indicator iz-button mat-flat-button mat-button-base mat-accent"]',
    edit_Img: 'mat-icon[mattooltip="Editar Encarte"]',
    excluir_Img: 'button[mattooltip="Cancelar"]',
    btn_salvarEncarte: 'button[class="mat-focus-indicator button-dark btn-new-entity mat-button mat-button-base"]',
    btn_cancelarExcluirImg : 'button[class="swal2-cancel swal2-styled"]',
    btn_confirmarExcluirImg : 'button[class="swal2-confirm swal2-styled"]',

    //acessos NPS
    txt_nomePesquisa: 'input[formcontrolname="nom_pesquisa"]',
    txt_objetivoPesquisa: 'textarea[formcontrolname="des_objetivo_pesquisa"]',
    seletor_pesquisa :'mat-select[formcontrolname="cod_nps_pegunta"]',
    txt_coment_pesquisa:'input[formcontrolname="des_pergunta"]',
    btn_proximo:'button[class="mat-focus-indicator button-dark mt-5 ml-0 mat-button mat-button-base"]',
    icon_cinza_pesquisa:'div[class="mat-tooltip-trigger info"]',
    icon_azul_pesquisa:'div[class="mat-tooltip-trigger info info-valid"]',
    txt_cad_inicial:'input[formcontrolname="dat_cad_inicio"]',
    txt_cad_final:'input[formcontrolname="dat_cad_final"]',
    text_genero_pesquisa:'input[placeholder="Gênero"]',
    text_personas_pesquisa:'input[placeholder="Personas"]',
    text_lojas_pesquisa:'input[placeholder="Lojas"]',
    ativarCheckbox:'span[class="mat-slide-toggle-bar"]',
    check_comunicarSMS_pesquisa:'input[id="mat-checkbox-2-input"]',
    btn_proximo_pesquisa: 'button[class="mat-focus-indicator button-dark next-step btn-next mat-button mat-button-base"]',
    text_hr_envio:'input[data-placeholder="Hora do envio"]',

    //acessos Pessoas
    inp_check_cadastro:'input[formcontrolname="bol_ativo"]',
    inp_check_permite:'input[formcontrolname="bol_utiliza_crm"]',
    inp_check_termo:'input[formcontrolname="bol_aceitou_termo"]',
    inp_check_privacidade:'input[formcontrolname="bol_aceitou_politica"]',
    inp_nome_pessoas:'input[data-placeholder="Nome completo"]',
    inp_nascimento_pessoas:'input[data-placeholder="Nascimento"]',
    inp_cpf_pessoas:'input[data-placeholder="CPF"]',
    inp_celular_pessoas:'input[data-placeholder="Celular"]',
    inp_email_pessoas:'input[data-placeholder="E-mail (Opcional)"]',
    inp_cep_pessoas:'input[data-placeholder="CEP"]',
    inp_endereco_pessoas:'input[formcontrolname="des_endereco"]',
    inp_numCurto_pessoas:'input[data-placeholder="Número"]',
    inp_bairro_pessoas:'input[data-placeholder="Bairro"]',
    a_voltar_pessoas: 'a[class="arrow-back"]',
    inp_pesquisar_pessoa: 'input[data-placeholder="Buscar por Nome, CPF ou ID"]',
    a_exportar_pessoas: 'a[class="export ng-star-inserted"]',
    inp_emailExportacao_pessoas: 'input[formcontrolname="des_email"]',
    icon_visualizar_pessoas:'mat-icon[class="mat-icon notranslate icon-view material-icons mat-icon-no-color"]',
    icon_editar_pessoas:'mat-icon[class="mat-icon notranslate icon-edit material-icons mat-icon-no-color"]',
    icon_excluir_pessoas:'mat-icon[class="mat-icon notranslate icon-delete material-icons mat-icon-no-color"]',
    filtrar_genero_pessoas:'input[placeholder="Gênero"]',
    btn_filtar_pessoas: 'button[class="mat-focus-indicator iz-button md mat-flat-button mat-button-base mat-primary"]'
}
export default RelacionamentoElements;
