name: Cypress Tests

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   # Runs “At 11:00 on every day-of-week from Monday through Friday. Consider UTC”
  #   - cron: '00 14 * * 1-5'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Checkout
      uses: actions/checkout@v3

  ui-chrome-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install
      uses: cypress-io/github-action@v5.6.1
      with:
        runTests: false
        
    - name: Write the cypress.env.json file
      run: |
        echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
    
    - name: 'UI Tests - Chrome'
      uses: cypress-io/github-action@v5.6.1
      with:
        install: false
        wait-on: "https://lab.izio.com.br/"
        wait-on-timeout: 120
        browser: chrome
        record: true
        parallel: true
        group: 'UI - Chrome'
        env: grepTags="@login @comunicacao"
        tag: tags
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}